### ISSUE TITLE
Syntax error when running from cmd

### ISSUE THREAD

**Issue by Warkorentin** [hastinbe/i3blocks-battery-plus#2]
Hi. I've been trying to use this script but can't get it to run correctly, even from a terminal. I installed all the dependencies but it doesn't seem to be the issue. I'm not a developer, could you point me in the right direction ? 

Here is the output that I'm getting : 

![image](https://user-images.githubusercontent.com/6535535/118241525-8b4e6280-b49c-11eb-9943-2a6e2a793e4d.png)

Thanks !

**Comment by hastinbe** [comment]
Sure, it looks like it's not able to get your current battery level. It could be that it's configured with an invalid battery (the `instance` in your config). A quick way is to run the command `upower -e` and look for symbols ending with battery_*, and specify what's after the _  as the instance value. Example:

```sh
$ upower -e
/org/freedesktop/UPower/devices/line_power_AC0
/org/freedesktop/UPower/devices/battery_BAT0
/org/freedesktop/UPower/devices/mouse_hidpp_battery_0
/org/freedesktop/UPower/devices/DisplayDevice
```

So I would then change my i3blocks.conf to use
```ini
[battery-plus]
instance=BAT0
```

**Comment by Warkorentin** [comment]
That's it ! 

`acpi -b` returned :

> Battery 0: Discharging, 91%, 07:04:12 remaining

So I assumed that I had to set my instance to `BAT0`, but `upower -e` gives me : 

> $ upower -e                                                                           
/org/freedesktop/UPower/devices/line_power_AC
/org/freedesktop/UPower/devices/battery_BAT1
/org/freedesktop/UPower/devices/line_power_ucsi_source_psy_USBC000o001
/org/freedesktop/UPower/devices/DisplayDevice

I switched from `BAT0` to `BAT1` and it now runs perfectly. 
Thanks a lot !
