### ISSUE TITLE
Impossible to disable icons

### ISSUE THREAD

**Issue by pathetic-lynx** [hastinbe/i3blocks-battery-plus#7]
With the script providing default values if the env var is unset it is impossible to explicitly disable some icons, maybe you want to consider adding a flag that suppresses this behavior.

**Comment by hastinbe** [comment]
Here's a quick and dirty way, maybe can expand on this later.. `-s` to suppress in d3e9f89de985c5d345c87e29868add140a816303

**Comment by pathetic-lynx** [comment]
That works for me, nice
